build_dashboard:
  fields:
    dashboard:
      required: true
      example: dashboard-finances
      selector:
        text:
    reset:
      default: false
      selector:
        boolean:
    language:
      selector:
        select:
          translation_key: dashboard_language
          options:
            - en
            - de
